### ISSUE TITLE
Windows 10 test fails

### ISSUE THREAD

**Issue by hearnsj** [JuliaImages/ImageView.jl#125]
I am really, realy sorry to open this issue.
I suspect something has gone wrong with a Windows 10 / Julia 0.6 installation.
However, I have removed Julia and my .Julia directory.
A fresh install from the Julia download site then:
Pkg.add("ImageView")
Pkg.test("ImageView")

has this result:

Test Summary: | Pass  Total
Canvas size   |    3      3
Test Summary: | Pass  Total
Aspect ratio  |    6      6
INFO: Could not find earth in directory. Checking if it exists in the online repository.
INFO: Found earth in the online repository. Downloading to the images directory.
Test Failed
  Expression: w <= ws && h <= hs
ERROR: LoadError: LoadError: There was an error during testing
while loading C:\Users\hearn\.julia\v0.6\ImageView\test\newtests.jl, in expression starting on line 79
while loading C:\Users\hearn\.julia\v0.6\ImageView\test\runtests.jl, in expression starting on line 10
==================================================[ ERROR: ImageView ]==================================================

failed process: Process(`'C:\Users\hearn\AppData\Local\Julia-0.6.0\bin\julia.exe' -Cx86-64 '-JC:\Users\hearn\AppData\Local\Julia-0.6.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\hearn\.julia\v0.6\ImageView\test\runtests.jl'`, ProcessExited(1)) [1]

========================================================================================================================
INFO: Removing ImageMagick v0.5.0
INFO: Removing TestImages v0.2.0
INFO: Removing ZipFile v0.4.0
ERROR: ImageView had test errors

**Comment by timholy** [comment]
That's not a very crucial test: it's just checking that ImageView is smart enough not to create a window that is much much bigger than your screen. Do you by any chance have a very large monitor?

Is ImageView working properly for you otherwise?

**Comment by hearnsj** [comment]
Tim, short answer is yes I do have a high resolution monitor (retina display)
If you want me to help in debugging with a high resolution display I am  happy to do that.
Further explanation:
I have an HP Spectre laptop with a 3840x2160 display (would be a Retina display in Apple speak)
In addition to Windows 10 I have a dual boot with Fedora 25.
The test of ImageView fails on Fedora/Julia 0.6  in the same place.
If I run that snippet from the REPL it runs OK.
I have a second display and if I put the image there it runs fine from the REPL also.
Out of interest:
ulia> w,h = size(win)
(1920, 1052)
julia> ws, hs = screen_size(win)
(5760, 2160)
julia> w <= ws && h <= hs
true

I note that ws=5760  not 3840 as the screen resolution is.  I wonder about an issue with Gtk

**Comment by timholy** [comment]
Yes, it sounds like there might be an issue with the reported resolution in Gtk.

However, for this test the thing to do is wrap it inside a check to make sure the image is bigger than the screen. Or we could randomly generate an image that's bigger than the screen, in which case it should always work.

**Comment by timholy** [comment]
This is pretty old, and it's passing on CI now.
