### ISSUE TITLE
Precompiling module ImageView failing on Ubuntu 17.10

### ISSUE THREAD

**Issue by philtomson** [JuliaImages/ImageView.jl#131]
Not sure if this is caused by the newness of Ubuntu 17.10 (new libgtk* libs?) or something else:

   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2-pre.0 (2017-10-25 17:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit ac16a870d3 (26 days old release-0.6)
|__/                   |  x86_64-linux-gnu

julia> using ImageView
INFO: Precompiling module ImageView.

signal (6): Aborted
while loading /home/phil/.julia/v0.6/ImageView/src/ImageView.jl, in expression starting on line 7
__libc_signal_restore_set at /build/glibc-CxtIbX/glibc-2.26/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80 [inlined]
raise at /build/glibc-CxtIbX/glibc-2.26/signal/../sysdeps/unix/sysv/linux/raise.c:48
abort at /build/glibc-CxtIbX/glibc-2.26/stdlib/abort.c:90
_Unwind_Resume at /lib/x86_64-linux-gnu/libgcc_s.so.1 (unknown line)
unknown function (ip: 0x7efe8b007112)
unknown function (ip: 0x7efe8b002a71)
unknown function (ip: 0x7efe8afe6ebe)
_ZN3mir6client30DefaultConnectionConfiguration15the_rpc_channelEv at /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (unknown line)
mir_connect at /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (unknown line)
mir_connect_sync at /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (unknown line)
unknown function (ip: 0x7efe8e97e8b8)
gdk_display_manager_open_display at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (unknown line)
gtk_init_with_args at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (unknown line)
#231 at /home/phil/.julia/v0.6/Gtk/src/events.jl:11
Type at /home/phil/.julia/v0.6/Gtk/src/GLib/gerror.jl:13
__init__ at /home/phil/.julia/v0.6/Gtk/src/events.jl:10
unknown function (ip: 0x7efe9858b16e)
jl_call_fptr_internal at /home/phil/build/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/phil/build/julia/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/phil/build/julia/src/gf.c:1926
jl_apply at /home/phil/build/julia/src/julia.h:1424 [inlined]
jl_module_run_initializer at /home/phil/build/julia/src/toplevel.c:87
jl_init_restored_modules at /home/phil/build/julia/src/dump.c:2443 [inlined]
_jl_restore_incremental at /home/phil/build/julia/src/dump.c:3317
jl_restore_incremental at /home/phil/build/julia/src/dump.c:3337
_include_from_serialized at ./loading.jl:157
_require_from_serialized at ./loading.jl:200
unknown function (ip: 0x7efe9857ea27)
jl_call_fptr_internal at /home/phil/build/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/phil/build/julia/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/phil/build/julia/src/gf.c:1926
_require_search_from_serialized at ./loading.jl:236
unknown function (ip: 0x7efe98584167)
jl_call_fptr_internal at /home/phil/build/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/phil/build/julia/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/phil/build/julia/src/gf.c:1926
_require at ./loading.jl:441
require at ./loading.jl:405
unknown function (ip: 0x7efe98577158)
jl_call_fptr_internal at /home/phil/build/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/phil/build/julia/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/phil/build/julia/src/gf.c:1926
jl_apply at /home/phil/build/julia/src/julia.h:1424 [inlined]
eval_import_path_ at /home/phil/build/julia/src/toplevel.c:403
eval_import_path at /home/phil/build/julia/src/toplevel.c:430 [inlined]
jl_toplevel_eval_flex at /home/phil/build/julia/src/toplevel.c:495
jl_toplevel_eval_flex at /home/phil/build/julia/src/toplevel.c:551
jl_eval_module_expr at /home/phil/build/julia/src/toplevel.c:205
jl_toplevel_eval_flex at /home/phil/build/julia/src/toplevel.c:480
jl_parse_eval_all at /home/phil/build/julia/src/ast.c:873
jl_load at /home/phil/build/julia/src/toplevel.c:616
include_from_node1 at ./loading.jl:576
unknown function (ip: 0x7efeb32c510b)
jl_call_fptr_internal at /home/phil/build/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/phil/build/julia/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/phil/build/julia/src/gf.c:1926
include at ./sysimg.jl:14
unknown function (ip: 0x7efeb315bbcb)
jl_call_fptr_internal at /home/phil/build/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/phil/build/julia/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/phil/build/julia/src/gf.c:1926
do_call at /home/phil/build/julia/src/interpreter.c:75
eval at /home/phil/build/julia/src/interpreter.c:242
jl_interpret_toplevel_expr at /home/phil/build/julia/src/interpreter.c:34
jl_toplevel_eval_flex at /home/phil/build/julia/src/toplevel.c:577
jl_toplevel_eval_in at /home/phil/build/julia/src/builtins.c:496
anonymous at ./<missing>:2
jl_call_fptr_internal at /home/phil/build/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/phil/build/julia/src/julia_internal.h:358 [inlined]
jl_toplevel_eval_flex at /home/phil/build/julia/src/toplevel.c:589
jl_toplevel_eval_in at /home/phil/build/julia/src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7efeb32818bf)
jl_call_fptr_internal at /home/phil/build/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/phil/build/julia/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/phil/build/julia/src/gf.c:1926
process_options at ./client.jl:286
_start at ./client.jl:371
unknown function (ip: 0x7efeb32d3b18)
jl_call_fptr_internal at /home/phil/build/julia/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/phil/build/julia/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/phil/build/julia/src/gf.c:1926
jl_apply at /home/phil/build/julia/ui/../src/julia.h:1424 [inlined]
true_main at /home/phil/build/julia/ui/repl.c:127
main at /home/phil/build/julia/ui/repl.c:264
__libc_start_main at /build/glibc-CxtIbX/glibc-2.26/csu/../csu/libc-start.c:308
unknown function (ip: 0x558a440db6f9)
unknown function (ip: 0xffffffffffffffff)
Allocations: 9422272 (Pool: 9420541; Big: 1731); GC: 17
ERROR: Failed to precompile ImageView to /home/phil/.julia/lib/v0.6/ImageView.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405

... I think it has something to do with 'using Gtk.ShortNames

Pkg.test("Gtk") also fails:
julia> Pkg.test("Gtk")
INFO: Testing Gtk

signal (6): Aborted
while loading /home/phil/.julia/v0.6/Gtk/test/../src/Gtk.jl, in expression starting on line 108
__libc_signal_restore_set at /build/glibc-CxtIbX/glibc-2.26/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80 [inlined]
raise at /build/glibc-CxtIbX/glibc-2.26/signal/../sysdeps/unix/sysv/linux/raise.c:48
abort at /build/glibc-CxtIbX/glibc-2.26/stdlib/abort.c:90
_Unwind_Resume at /lib/x86_64-linux-gnu/libgcc_s.so.1 (unknown line)
unknown function (ip: 0x7f753fcfc112)
unknown function (ip: 0x7f753fcf7a71)
unknown function (ip: 0x7f753fcdbebe)
_ZN3mir6client30DefaultConnectionConfiguration15the_rpc_channelEv at /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (unknown line)
mir_connect at /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (unknown line)
mir_connect_sync at /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (unknown line)
unknown function (ip: 0x7f7541f058b8)
gdk_display_manager_open_display at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (unknown line)
gtk_init_with_args at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (unknown line)
#231 at /home/phil/.julia/v0.6/Gtk/test/../src/events.jl:11
Allocations: 5384156 (Pool: 5382829; Big: 1327); GC: 10
=======================================================[ ERROR: Gtk ]=======================================================

failed process: Process(`/home/phil/build/julia/usr/bin/julia -Cnative -J/home/phil/build/julia/usr/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /home/phil/.julia/v0.6/Gtk/test/runtests.jl`, ProcessSignaled(6)) [0]

============================================================================================================================
ERROR: Gtk had test errors

**Comment by timholy** [comment]
Does `using Gtk` work? If not, it would be worth closing this and reporting as a Gtk.jl issue.

**Comment by philtomson** [comment]
Nope: 
julia> using Gtk

signal (6): Aborted
while loading no file, in expression starting on line 0
__libc_signal_restore_set at /build/glibc-CxtIbX/glibc-2.26/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80 [inlined]
raise at /build/glibc-CxtIbX/glibc-2.26/signal/../sysdeps/unix/sysv/linux/raise.c:48
abort at /build/glibc-CxtIbX/glibc-2.26/stdlib/abort.c:90
_Unwind_Resume at /lib/x86_64-linux-gnu/libgcc_s.so.1 (unknown line)
unknown function (ip: 0x7f668124b112)
unknown function (ip: 0x7f6681246a71)
unknown function (ip: 0x7f668122aebe)
_ZN3mir6client30DefaultConnectionConfiguration15the_rpc_channelEv at /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (unknown line)
mir_connect at /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (unknown line)
mir_connect_sync at /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (unknown line)
unknown function (ip: 0x7f6684bc28b8)
gdk_display_manager_open_display at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (unknown line)
gtk_init_with_args at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (unknown line)
#231 at /home/phil/.julia/v0.6/Gtk/src/events.jl:11
Allocations: 1704240 (Pool: 1703032; Big: 1208); GC: 1
Aborted (core dumped)

**Comment by timholy** [comment]
Until you have Gtk.jl working, ImageView doesn't have a chance of working. So I'll close. I sometimes help out over at Gtk too, but I'm pretty swamped right now so hopefully someone else will have time to figure it out.
