### ISSUE TITLE
Rubberband zoom offset

### ISSUE THREAD

**Issue by Cody-G** [JuliaImages/ImageView.jl#141]
I'm pretty sure this is a problem upstream of ImageView.  When I draw a rectangle for zooming in on a region of an image, the rectangle is offset from the point of my click.  The offset is smallest when I drag in the upper left portion of the canvas, and it grows as I move closer to the bottom right.  To me this would suggest some improper scaling of user and device coordinates.  The bizarre thing is that this is only happening on one of my two machines, even though both of them have the same ~julia packages~ and GTK libraries installed.  The only other clue I have is that the misbehaving machine also fails some GtkReactive tests related to coordinates (see https://github.com/JuliaGizmos/GtkReactive.jl/issues/67).  The machine does however pass all of the Gtk.jl tests.

**Comment by Cody-G** [comment]
Downgrading Cairo to v0.4.0 works around the issue.  The inspiration was from [here](https://github.com/JuliaImages/ImageView.jl/issues/139), though that issue doesn't seem closely related.

**Comment by timholy** [comment]
Fixed by https://github.com/JuliaGraphics/Cairo.jl/pull/254
