### ISSUE TITLE
Can't reach Playback context menu for changing FPS

### ISSUE THREAD

**Issue by Clocktown** [JuliaImages/ImageView.jl#144]
I can't seem to reach the context menu that allows to edit the playback rate, added back in commit [c781ce1](https://github.com/JuliaImages/ImageView.jl/commit/c781ce16ae08f5db472d5ec470bc54bf04c9e4a1).  

I tried right-clicking basically anywhere (the buttons, the slider, the background...).  
This is on Windows 10, it might be a platform related issue.  

See also #4 where @rsrock mentions this in his last comment.  

I do have to say though: GREAT work with this library! I'm amazed that there even is a playback feature. You seem to have every feature I could imagine in here.

**Comment by timholy** [comment]
This was probably for a non-grayscale image. Originally contrast was manipulable only for grayscale, but it has since been added for RGB too.
