### ISSUE TITLE
Wrong hoverinfo

### ISSUE THREAD

**Issue by yakir12** [JuliaImages/ImageView.jl#148]
After creating a 500x500 pixel image and displaying it:
```julia
using ImageView
imshow(rand(500, 500))
```
I found out that the `hoverinfo` is wrong by ~50 pixels regardless of the size of the displayed image (the cursor was at the bottom-right corner of the image before this screenshot):
![screenshot_2018-06-26_12 00 53](https://user-images.githubusercontent.com/3281957/41906680-c8c1cd38-793e-11e8-9b73-6f44d231d6ad.png)

BTW: I posted [an identical post](https://discourse.julialang.org/t/strange-glitch-in-imageview-hoverinfo/11959?u=yakir12) on Discourse.

**Comment by yakir12** [comment]
Platform: 
```
Debian 4.9.88-1+deb9u1 (2018-05-07)
```
Julia: 
```
version 0.6.3 (2018-05-28 20:20 UTC)
```
Packages:
```julia
Gtk=>v"0.14.0"        
Cairo=>v"0.5.2"       
Reactive=>v"0.7.0+"   
GtkReactive=>v"0.3.0+"
ImageView=>v"0.6.0"  
```

**Comment by timholy** [comment]
Hmm, try unsticking your GtkReactive? For me
```julia
"Gtk"=>0.14.0
"Cairo"=>0.5.2
"Reactive"=>0.7.0
"GtkReactive"=>0.4.1
"ImageView"=>0.6.0
```

**Comment by yakir12** [comment]
Whaaat... Of course you are right.
Fixed and it's all good now. 
Thanks a billion!
