### ISSUE TITLE
REPL becomes heavy after importing ImageView

### ISSUE THREAD

**Issue by Dsuke-K** [JuliaImages/ImageView.jl#159]
When I used ImageView in REPL in Julia 1.0.1 on Windows 10, REPL's response became slow after importing this library. Characters are displayed but delayed than usual. While the response become heavy, Julia's performance was almost no change.

```
julia> using Images, TestImages, ImageFiltering
julia> using BenchmarkTools
julia> img = testimage("")
julia> imfilter(img, KernelFactors.gaussian((3, 3)))
julia> @btime imfilter(img, KernelFactors.gaussian((3, 3)))
  5.747 ms (301 allocations: 4.13 MiB)

julia> using ImageView
julia> @btime imfilter(img, KernelFactors.gaussian((3, 3)))
  5.733 ms (301 allocations: 4.13 MiB)

julia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

Please forgive me that I'm not sure how to measure the `REPL's response time`...

**Comment by timholy** [comment]
I know it's hard to measure, but are you talking 0.1s per character or 1s per character or something else? 

I don't see this on Linux. Does this always happen for you? Any chance your machine just ran out of RAM and began swapping it to disk?

**Comment by Dsuke-K** [comment]
It's around 0.1s or so on.  I also used this module in OSX on MBP, but did not happen at all. This heavy response happens always on both my desktop (shown above) and another laptop PC (less CPU power and RAM), both are Win 10 pro.

> Any chance your machine just ran out of RAM and began swapping it to disk?

My desktop PC has 16GB RAM, and its usage was around 50% or so on, so it is unlikely that RAM is the cause.

**Comment by timholy** [comment]
Does it happen if you just say `using Gtk`? Maybe it's the Gtk event loop. If just using the package doesn't trigger the problem, also try [a simple demo](http://juliagraphics.github.io/Gtk.jl/latest/manual/gettingStarted.html) and see if that gives you the same effect.

**Comment by Dsuke-K** [comment]
As you mentioned, `using Gtk ` caused the lags. This issue was reported at Julia 0.6.0, and seems to be still open.

https://github.com/JuliaGraphics/Gtk.jl/issues/325

Thanks.

**Comment by timholy** [comment]
Since this is a Gtk issue I'll close.
