### ISSUE TITLE
Support mp4 files

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaImages/ImageView.jl#163]
Right now `load("file.mp4")` yields
```
ERROR: FileIO.File{FileIO.DataFormat{:UNKNOWN}}("file.mp4") couldn't be recognized by FileIO.
```

**Comment by timholy** [comment]
Try [VideoIO](https://github.com/kmsquire/VideoIO.jl).

This isn't really an ImageView issue, it's a VideoIO & FileIO issue, so I'll close.
