### ISSUE TITLE
Coordinate marker stops working

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaImages/ImageView.jl#164]
When viewing a picture with `imshow` the coordinates of the mouse are displayed in the lower left corner of the image. That is really helpful. However, after showing an image with a different number type than those before, the tracking of the cursor does not work anymore for the previous picture.

**Comment by BeastyBlacksmith** [comment]
Ok, now it is working with two pictures with different types, but fails on a third, so I don't really know yet what the cause is.

**Comment by timholy** [comment]
Probably already fixed by #162, try upgrading your packages

**Comment by timholy** [comment]
Ah, wait, it needs a new GtkReactive and https://github.com/JuliaLang/METADATA.jl/pull/20029 hasn't been merged yet.

**Comment by BeastyBlacksmith** [comment]
As far as I can tell, the issue is resolved. Thanks :)
