### ISSUE TITLE
Wrong window size information

### ISSUE THREAD

**Issue by rapus95** [JuliaImages/ImageView.jl#165]
![image](https://user-images.githubusercontent.com/5960902/50223023-53f62d00-039a-11e9-8e8c-e5cda8ee80f5.png)
As you can see the Print Window Function(alt+print) of windows seems to expect a larger frame than it actually is. (Border around the frame where you can see the background)

**Comment by jwahlstrand** [comment]
This is still the case five years later, but I'm going to close this because it's an issue with GTK on Windows and not this package (or any Julia package).

**Comment by rapus95** [comment]
I'd suggest to not close it as "completed" then but as "won't fix" or similar
