### ISSUE TITLE
test with master does not exit cleanly

### ISSUE THREAD

**Issue by colbec** [JuliaImages/ImageView.jl#167]
Using:
```
julia> versioninfo()
Julia Version 1.3.0-DEV.20
Commit 63ab10104c (2019-04-12 20:53 UTC)
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```
when testing ImageView the test gets to the point of "Non-AbstractArrays", then the system goes quiet (cpu and memory no further activity) but windows are left scattered on the screen. This only happens with master; with Julia binary as provided the testing procedure cleans up all the windows and exits as expected. All tests appear to have been completed without issue, and no error is produced, but the screen is prevented from subsequent cleanup; user has to kill the Julia instance and this clears up the windows.

**Comment by timholy** [comment]
Simpler reproducer:
```julia
julia> using TestImages, ImageView, Gtk

julia> img = testimage("light");

julia> dct = imshow(img);

julia> ImageView.closeall()
```

**Comment by colbec** [comment]
In current master `Version 1.4.0-DEV.527 (2019-11-26)` Tim's simpler reproducer above now works with the single image (and multiple lighthouse images) deleted with the `closeall` instruction, so I am closing this. Test still fails however for a different reason so I will start a new issue.

I see that `GtkReactive` was recently updated which may explain why `closeall` now works.
