### ISSUE TITLE
Error occurred when calling up contrast menu

### ISSUE THREAD

**Issue by Animadversio** [JuliaImages/ImageView.jl#168]
System: Windows 10 
Julia: 1.1.0
[86fae568] ImageView v0.8.2
[916415d5] Images v0.17.3

When I was visualizing a 3d dataset from an image file (the "ZBB_HuC-Cer" dataset from https://engertlab.fas.harvard.edu/Z-Brain/downloads/Harvard_MH_Database.hdf5), the visualization looks good at first.
> julia> imshow(img)
Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}("window"=>GtkWindowLeaf(name="", parent, width-request=-1, height-request=-1, visib…
  "roi"         => Dict{String,Any}("redraw"=>55: "map(clim-mapped image, input-3)" = nothing Nothing ,"zoomregion"=>2:…
  "annotations" => 4: "input-3" = Dict{UInt64,Any}() Dict{UInt64,Any}
  "clim"        => 3: "CLim" = CLim{RUInt16}(0x0000, 0x32d5) CLim{RUInt16}

And when I call up the contrast window the 2nd time, it throws such error and 

> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x63a5712a -- g_signal_handler_disconnect at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
in expression starting at no file:0
g_signal_handler_disconnect at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_signal_emit_valist at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_signal_emit at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_object_unref at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_object_new_valist at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_object_new at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
gtk_requisition_copy at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgtk-3-0.DLL (unknown line)
unknown function (ip: 000000006640229C)
gdk__private__ at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgdk-3-0.dll (unknown line)
g_main_context_dispatch at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libglib-2.0-0.dll (unknown line)
g_main_context_dispatch at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libglib-2.0-0.dll (unknown line)
g_main_loop_run at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libglib-2.0-0.dll (unknown line)
gtk_main at C:\Users\binxu\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgtk-3-0.DLL (unknown line)
#237 at C:\Users\binxu\.julia\packages\Gtk\RwVPb\src\events.jl:2
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1864
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
g_sigatom at C:\Users\binxu\.julia\packages\Gtk\RwVPb\src\GLib\signals.jl:167
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1864
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56
gtk_main at C:\Users\binxu\.julia\packages\Gtk\RwVPb\src\events.jl:1
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1864
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:572
Allocations: 68306645 (Pool: 68298847; Big: 7798); GC: 210

With a crashed contrast window. 
![image](https://user-images.githubusercontent.com/28660472/56453873-27cdc700-630e-11e9-9e44-2336454e56e1.png)

This is quite reproducible, still not sure how to interpret the error output. 
Thanks for helping!

**Comment by timholy** [comment]
Thanks for the report! I will fix. In the meantime you can work around this by changing the displayed frame while the original contrast GUI window is still open.

**Comment by Animadversio** [comment]
Thanks for the fixing! Really appreciate it!
