### ISSUE TITLE
Typing in REPL becomes laggy after using ImageView

### ISSUE THREAD

**Issue by coldinjection** [JuliaImages/ImageView.jl#176]
ImageView works correctly, but typing in REPL becomes laggy after ImageView is imported. It takes about half a second for REPL to react when I press any key on the keyboard. The same issue also  happens when I use JuliaPro. I'm using Windows 10.

**Comment by coldinjecition** [comment]
It seem this problem is actually generated by Gtk

**Comment by rapus95** [comment]
https://github.com/JuliaGraphics/Gtk.jl/issues/325 There's an issue for it. Sadly no updates :/

**Comment by timholy** [comment]
Might be worth trying on Julia 1.3 now that Gtk 1.0 is out

**Comment by rapus95** [comment]
> Might be worth trying on Julia 1.3 now that Gtk 1.0 is out

https://github.com/JuliaGraphics/Gtk.jl/pull/454
according to that, the problem hasn't been resolved lately

**Comment by timholy** [comment]
Should be fixed now.
