### ISSUE TITLE
Pan drag broken?

### ISSUE THREAD

**Issue by vsaase** [JuliaImages/ImageView.jl#179]
Hi,
Julia newbie here. When running the example with the MRI image, rubberband zooming is working fine, but `pan_drag` is not. 
Doing a `push!(dc["pan_drag]["enabled"], true)` where `dc` is returned from `imshow` doesnt solve it as it seems to be already enabled. I also tried to set the activation to first button press with shift key, and to disable `zoom_rubberband`.
How would I go about debugging this? Up to now I only know about @Juno.enter to start debugging a function, but this doesn't seem to work with GtkReactive.

best,
victor

**Comment by timholy** [comment]
Hmm, that's odd---seems to work for me. You're zooming in first and then panning? Panning won't let you go beyond the edges of the image, so it only becomes relevant when you've zoomed in enough that you're looking at a subset of the image.

**Comment by vsaase** [comment]
you're right of course. sorry for that. i am coming from radiology where you can usually always pan

**Comment by timholy** [comment]
No worries! Perhaps we should allow it, is there an advantage to doing so?
