### ISSUE TITLE
Is it possible to install with Cairov0.7.0 (#master)

### ISSUE THREAD

**Issue by mirestrepo** [JuliaImages/ImageView.jl#180]
Hi, 

I've been eagerly following the BinaryBuilder changes for [Cairo](https://github.com/JuliaGraphics/Cairo.jl/pull/292). There are a lot of mentions to incompatibility with Gtk. Since this package depends on both Cairo and Gtk, is there a knonw path to get ImageView working with the Cairo#master (soon to be v0.7.0)? I'm a Mac OS user.

Thanks for any tips

**Comment by timholy** [comment]
Regretfully not yet. @staticfloat, I lack any sense of how close/far we are to making Gtk a BB thing. I know you are working hard in this area, does your crystal ball reveal any hints?

Note that there are reports of some people getting the old version of Cairo working on macOS, one of the more successful seems to be https://github.com/JuliaGraphics/Cairo.jl/issues/271#issuecomment-476827465. Maybe that would hold you over?

**Comment by staticfloat** [comment]
I am very pleased to report that we have made very good progress with regards to BB-ified Gtk on Julia 1.3.  You can try it out yourself with the Manifest.toml hosted at [my GtkArtifactTest](https://github.com/staticfloat/GtkArtifactTest) repository; just use Julia 1.3-rc4 or later, instantiate, and run the test script to see if the "Face of Victory" image pops up.  It uses Artifacts all the way down, so no BinaryProvider should be needed at all if you use all of those branches, once 1.3 is actually released, we will move forward on getting those branches merged/compat bounds updated.

**Comment by timholy** [comment]
And because GitHub just doesn't provide enough reaction emojis: :fireworks: :sparkle: :star: :exclamation: :boom: :smile:

**Comment by timholy** [comment]
This really is huge. Dang I am happy about this. Makes my whole month!

**Comment by timholy** [comment]
Should be fixed if you use Julia 1.3 and up-to-date packages
