### ISSUE TITLE
cos(BigFloat(x)) is not working anymore after: using ImageView

### ISSUE THREAD

**Issue by rtdietrich** [JuliaImages/ImageView.jl#181]
Type this in Julia 1.3:
julia> **cos(BigFloat(3))** 
-0.9899924966004454572715727947312613023936790966155883288140859329283291975131371
julia> **import Pkg**
julia> **Pkg.add("ImageView")**
...
julia> **using ImageView**
julia> **cos(BigFloat(3))** 
Error showing value of type BigFloat:
ERROR: AssertionError: length(int) == 1
Stacktrace:
 [1] _prettify_bigfloat(::String) at .\mpfr.jl:993
 [2] _string at .\mpfr.jl:1003 [inlined]
 [3] _string at .\mpfr.jl:1005 [inlined]
... and many more Output...

**Am I doing something wrong or is this a serious error?**

**Comment by timholy** [comment]
Works fine for me on 1.4.0-DEV.177. I haven't tried 1.3, which specific version are you on?

**Comment by rtdietrich** [comment]
Working under Win10 and testing it right now with:
![Screenshot (79)](https://user-images.githubusercontent.com/13079745/66033832-59c39600-e508-11e9-8c80-9903493111b1.png)

**Comment by rtdietrich** [comment]
Additionally I uninstall Julia 1.2 and install Julia 1.3.0 rc2.0 under WIN10:

**Here it comes exactly to the same problem**

**Comment by rtdietrich** [comment]
even tried it with 1.4.0.DEV.242 2019-10-02 ->> Same Issue :-(

Full Error Output:
![Julia-Issue](https://user-images.githubusercontent.com/13079745/66139670-1c8eff00-e601-11e9-8151-9891a83dd9ea.png)

**Comment by timholy** [comment]
I only have access to a VirtualBox installation of Windows. I tested binaries of both julia 1.0.3 and 1.3.0-rc2 and cannot replicate this. Sorry, but you may have to report this as a Julia bug if you can't figure out what's wrong on your own.
