### ISSUE TITLE
imshow() Gtk/.../GLib.jl:29 cfunction_ could not load library "libjulia"

### ISSUE THREAD

**Issue by RocketRoss** [JuliaImages/ImageView.jl#213]
Hello. A minimal example of:
`using Images, TestImages, ImageView; rgb_image = testimage("lighthouse"); imshow(rgb_image);`

produces an error:

> ERROR: error compiling cfunction_: could not load library "libjulia"
> libjulia.so: cannot open shared object file: No such file or directory
> Stacktrace:
>  [1] cfunction_ at ***/.julia/packages/Gtk/mVhmL/src/GLib/GLib.jl:29 [inlined]
>  [2] signal_connect_generic(::Function, ::Gtk.GtkCanvas, ::String, ::Type{Nothing}, ::Tuple{}, ::Bool, ::Gtk.GtkCanvas) at ***/.julia/packages/Gtk/mVhmL/src/GLib/signals.jl:11
>  [3] signal_connect at ***/.julia/packages/Gtk/mVhmL/src/GLib/signals.jl:6 [inlined] (repeats 2 times)
>  [4] Gtk.GtkCanvas(::Int64, ::Int64) at ***/.julia/packages/Gtk/mVhmL/src/cairo.jl:20
>  [5] (::getfield(GtkReactive, Symbol("##call#157#158")))(::Bool, ::Type{GtkReactive.Canvas{GtkReactive.UserUnit}}, ::Int64, ::Int64) at ***/.julia/packages/GtkReactive/YcoHq/src/graphics_interaction.jl:235
>  [6] Type at ***/.julia/packages/GtkReactive/YcoHq/src/graphics_interaction.jl:235 [inlined]
>  [7] canvas at ***/.julia/packages/GtkReactive/YcoHq/src/graphics_interaction.jl:259 [inlined] (repeats 2 times)
>  [8] frame_canvas at ***/.julia/packages/ImageView/Pi4jH/src/ImageView.jl:374 [inlined]
>  [9] #imshow_gui#26(::String, ::Symbol, ::ImageView.SliceData{false,0,Tuple{}}, ::Function, ::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}) at ***/.julia/packages/ImageView/Pi4jH/src/ImageView.jl:316
>  [10] #imshow_gui#31 at ./none:0 [inlined]
>  [11] (::getfield(ImageView, Symbol("#kw##imshow_gui")))(::NamedTuple{(:name, :aspect),Tuple{String,Symbol}}, ::typeof(imshow_gui), ::Tuple{Int64,Int64}, ::ImageView.SliceData{false,0,Tuple{}}) at ./none:0
>  [12] #imshow#17(::Any, ::Any, ::Any, ::AbstractArray, ::Any, ::Reactive.Signal{GtkReactive.ZoomRegion{RoundingIntegers.RInt64}}, ::ImageView.SliceData, ::Any) at ***/.julia/packages/ImageView/Pi4jH/src/ImageView.jl:204
>  [13] #imshow at ./none:0 [inlined] (repeats 2 times)
>  [14] #imshow#13(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::AbstractArray) at ***/.julia/packages/ImageView/Pi4jH/src/ImageView.jl:179
>  [15] imshow(::AbstractArray) at ***/.julia/packages/ImageView/Pi4jH/src/ImageView.jl:176
>  [16] top-level scope at none:0

The 'libjulia' files were found: 
/usr/lib/x86_64-linux-gnu/libjulia.so.1
/usr/lib/x86_64-linux-gnu/julia
/usr/lib/x86_64-linux-gnu/libjulia.so.1.0

As a temporary measure I tried creating some symlinks to the /usr/lib folder, but to no avail.

Any suggestions/queries?

System details:
Julia Version 1.0.4
Ubuntu ⛬  julia/1.0.4+dfsg-1

`$ uname -r`
> 5.3.0-7629-generic

`$ cat /proc/version`
> Linux version 5.3.0-7629-generic (buildd@lgw01-amd64-033) (gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)) #31~1581628825~19.10~f90b7d5-Ubuntu SMP Fri Feb 14 19:56:45 UTC

(Pop!_os based on Ubuntu 19.10)

Edited: provided further information on my amateurish attempts at resolving this.

**Comment by johnnychen94** [comment]
How is Julia installed, via apt-get or by downloading julia binaries?

Can you verify that the same issue happens on Julia 1.3?

**Comment by RocketRoss** [comment]
I installed via apt-get.

I'll target the julia binaries (1.3) and respond.

Thanks

**Comment by johnnychen94** [comment]
> I installed via apt-get.

If you find installing Julia manually troublesome, you can try https://github.com/johnnychen94/jill.py

**Comment by RocketRoss** [comment]
Working on Julia Version 1.3.1 (2019-12-30).

Out of curiosity will quickly run again on Julia 1.5 from binaries and edit this post.

Thanks again

**Comment by johnnychen94** [comment]
Great, I'm closing it as it's not an ImageView issue.
