### ISSUE TITLE
Unable to compile ImageView under Julia 1.3.1 and 1.4

### ISSUE THREAD

**Issue by vepiteski** [JuliaImages/ImageView.jl#217]
```
julia> using ImageView
[ Info: Precompiling ImageView [86fae568-95e7-573e-a6b2-d8a6b900c9ef]
ERROR: LoadError: LoadError: InitError: could not load library "/home/dussault/.julia/artifacts/3cd20f6135e742ca5c9828e2965ae5b858721ad0/lib/libexslt.so"
/usr/lib/x86_64-linux-gnu/libxslt.so.1: version `LIBXML2_1.1.30' not found (required by /home/dussault/.julia/artifacts/3cd20f6135e742ca5c9828e2965ae5b858721ad0/lib/libexslt.so)
Stacktrace:
```
I tried in a fresh project with both Julia versions, the error is the same.

Previous to a forced recompile, my version 0.10.4 was running on 1.3.1 . I am stuck since the recompile.

Thanks!
JPD

**Comment by johnnychen94** [comment]
Could you share the output of `versioninfo()`?

How's your Julia installed? Using the system package manager(e.g., `apt`, `pacman`) or downloading binaries from julialang.org? Installing Julia using `apt`s can sometimes be problematic.

Can you confirm this issue still exists in the latest ImageView version, i.e., `v0.10.8`?

**Comment by vepiteski** [comment]
Le 20-04-23 à 21 h 21, Johnny Chen a écrit :
>
> Could you share the output of |versioninfo()|?
>
    julia> versioninfo()
    Julia Version 1.3.1
    Commit 2d5741174c (2019-12-30 21:36 UTC)
    Platform Info:
       OS: Linux (x86_64-pc-linux-gnu)
       CPU: Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz
       WORD_SIZE: 64
       LIBM: libopenlibm
       LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

and

    julia> versioninfo()
    Julia Version 1.4.0
    Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
    Platform Info:
       OS: Linux (x86_64-pc-linux-gnu)
       CPU: Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz
       WORD_SIZE: 64
       LIBM: libopenlibm
       LLVM: libLLVM-8.0.1 (ORCJIT, haswell)



> How's your Julia installed? Using the system package manager(e.g., 
> |apt|, |pacman|) or downloading binaries from julialang.org? 
> Installing Julia using |apt|s can sometimes be problematic.
>
I get the binaries from Julialang.org.


> Can you confirm this issue still exists in the latest ImageView 
> version, i.e., |v0.10.8|?
>

(@v1.4) pkg> status ImageView
Status `~/.julia/environments/v1.4/Project.toml`
   [86fae568] ImageView v0.10.8

julia> using ImageView
[ Info: Precompiling ImageView [86fae568-95e7-573e-a6b2-d8a6b900c9ef]
ERROR: LoadError: LoadError: InitError: could not load library 
"/home/dussault/.julia/artifacts/3cd20f6135e742ca5c9828e2965ae5b858721ad0/lib/libexslt.so"
/usr/lib/x86_64-linux-gnu/libxslt.so.1: version `LIBXML2_1.1.30' not 
found (required by 
/home/dussault/.julia/artifacts/3cd20f6135e742ca5c9828e2965ae5b858721ad0/lib/libexslt.so)

**Comment by timholy** [comment]
This is a weird one. I lack the expertise to figure this out, perhaps try filing an issue with https://github.com/JuliaBinaryWrappers/XSLT_jll.jl (and link back to this issue report).

**Comment by vepiteski** [comment]
Thanks, I did file such an issue.
HOWEVER, I created a new user account on the same machine and in a fresh Julia 1.4.1 setup, I do not get the error. Unfortunately, in this fresh installation, I get a pyplot issue which I do not get in my usual setup.

**Comment by giordano** [comment]
Does the error happen in a fresh Julia session?  The fact that `/usr/lib/x86_64-linux-gnu/libxslt.so.1` appears in the error message suggests this library had been loaded by something else.  How did you install Julia?

**Comment by timholy** [comment]
These aren't supported versions of Julia anymore, and ImageView compiles well on newer Julia versions.
