### ISSUE TITLE
Update pixel value while changing image with keys

### ISSUE THREAD

**Issue by roflmaostc** [JuliaImages/ImageView.jl#218]
Hey,

when I'm using the mouse to inspect the value of a certain pixel (left bottom corner) and trying to switch between different images, it doesn't update the pixel value.
To get the updated pixel value, I need to slightly move the mouse that the value gets an update.

Is it possible to also update this value when one presses the arrow keys to switch images?

Thanks,

Felix

**Comment by jwahlstrand** [comment]
This seems to work as desired in recent versions.
