### ISSUE TITLE
Mouse zooming and panning feature lost after running imshow!()

### ISSUE THREAD

**Issue by Predator268** [JuliaImages/ImageView.jl#242]
I am trying to create an interface that allows the user to move through different images automatically in the same window so am using ```imshow!(GUIdict["gui"]["canvas"], GtkReactive.Signal(imgs2[:,:,1]))``` where ```GUIdict``` is assigned as ```imshow(imgs)``` when opening the first image. However, after running ```imshow!(...)```, the zooming feature using the mouse does not work. How can I enable the zoom feature after running ```imshow!(...)```?

**Comment by timholy** [comment]
I'd need a reproducible example to try it myself, but in general terms the most likely culprit is garbage-collection. Read https://juliagizmos.github.io/GtkReactive.jl/stable/#Concepts-1

**Comment by Predator268** [comment]
@timholy thanks for the link. Managed to solve my problem using that. Was following an outdated version of the guide and so had ```set_coords``` instead of ```set_coordinates```.
