### ISSUE TITLE
Image Clipping Algorithms

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaImages/ImageView.jl#245]
Clipping in computer graphics is to remove objects, lines, or line segments that are outside the viewing pane.
In line clipping, we will cut the portion of line which is outside of window and keep only the portion that is inside the window
Will be quite useful for ImageView and,best application would be to cut and download selected pieces from a image.
Polygon clipping would be the pretty useful for other purposes too in my opinion,since it will be most flexible. For example: https://github.com/JuliaImages/ImageDraw.jl/issues/53

- Cohen-Sutherland Line Clippings
- Cyrus-Beck Line Clipping Algorithm
- Polygon Clipping SutherlandHodgmanAlgorithm

References: 
- https://www.tutorialspoint.com/computer_graphics/viewing_and_clipping.htm
- https://www.javatpoint.com/computer-graphics-clipping
- https://www.geeksforgeeks.org/cohen-sutherland-vs-liang-barsky-line-clipping-algorithm

**Comment by ashwani-rathee** [comment]
An important issue would be able to pin points(vertices) in the image in ImageView imshow tool then use imagedraw.jl with it.I'm not sure if it's already there.That will increase the interactivity scope by quite a lot imo.

**Comment by timholy** [comment]
Tinker.jl has been the intended target for a drawable interactive canvas based on ImageView. Can you move this issue there?
