### ISSUE TITLE
GTK error it seems like a bug

### ISSUE THREAD

**Issue by develooper1994** [JuliaImages/ImageView.jl#258]
bug breaks Julia interpreter!!!

(julia.exe:2924): Gtk-WARNING **: 17:08:45.798: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load <home>\.julia\artifacts\65eca7c48dea1e32203b205613441ce9506045b4\share\icons\Adwaita\16x16/status\image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_BREAKPOINT at 0x7ffbee7d5702 -- DebugBreak at C:\WINDOWS\System32\KERNELBASE.dll (unknown line)
in expression starting at REPL[126]:1
DebugBreak at C:\WINDOWS\System32\KERNELBASE.dll (unknown line)
Allocations: 2308901771 (Pool: 2307491943; Big: 1409828); GC: 529
send: No error

[process exited with code 1]

**Comment by timholy** [comment]
Hmm, I don't see this. Can you try updating your Gtk.jl, possibly with `Pkg.build("Gtk")`?

**Comment by develooper1994** [comment]
I think i solved it by updating packages for now.
