### ISSUE TITLE
ImageView grinds Windows to a hold

### ISSUE THREAD

**Issue by RainerHeintzmann** [JuliaImages/ImageView.jl#287]
A Pluto Notebook on a Windows 10 PC using Julia 1.9 and Pluto 0.19.28 with only the following line in the Pluto notebook:
`using ImageView`
is enough to (almost) grind my computer to a halt. Typing any letter on the keyboard in any program has about 1-5 seconds delay to take effekt. Presumably this is some GTK issue. I set `NUM_THREADS` to `any` in my environment.
I think this is a windows-only problem.

**Comment by RainerHeintzmann** [comment]
I stumbled over this, since it was in the list of a published Pluto-Notebook. But I guess the idea was to have some interactive image control within Pluto.

**Comment by ashwani-rathee** [comment]
For interactive with Images through Pluto, this pluto notebook might be of interest too sir: https://gist.github.com/ashwani-rathee/4211eec75ebdc8becd31ac1c38f50a6b

**Comment by mkitti** [comment]
Are we doing anything with interactive threads yet?

**Comment by ashwani-rathee** [comment]
Ones with channels and producers? I could have example ready for that, something like done here: https://medium.com/@ashwanirathee/2-way-communication-with-microcontrollers-using-c-and-julia-611e37c18da7, an example I can think of is getting data from rtsp stream and then processing it, which is doable too.

**Comment by mkitti** [comment]
Does the `ENV["GTK_AUTO_IDLE"] = false` trick apply here?

**Comment by mkitti** [comment]
No, I mean the new Julia 1.9 interactive thread pool.

**Comment by jwahlstrand** [comment]
> Does the `ENV["GTK_AUTO_IDLE"] = false` trick apply here?

That should work if it's just https://github.com/JuliaGraphics/Gtk.jl/issues/629

In any case the Gtk4 port should be ready soon.

**Comment by jwahlstrand** [comment]
Just released version 0.12.0 hopefully fixes this.
