### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by lucasb-eyer** [JuliaImages/ImageView.jl#37]
Run `view(zeros(100,100))` and you'll get a window with 100x100-sized content. The problem is that the content itself only is 100x84, because the "statusbar" has a height of 16.

I wanted to write a PR that adds 16 to [`whfull`](https://github.com/timholy/ImageView.jl/blob/master/src/display.jl#L241), but I don't think the `xypos` label's height is fixed to 16 anywhere in code and I couldn't find any obvious way of fixing it.

**Comment by timholy** [comment]
Fixed, I believe.
