### ISSUE TITLE
Nicer way to open and update windows

### ISSUE THREAD

**Issue by kmsquire** [JuliaImages/ImageView.jl#40]
To display videos in `VideoIO`, I find that I have to read an image, open a window to display it in order to get a handle the canvas, and then use that handle inside a loop.

It would be nice if either
1. The window could be opened without supplying an image (is this already possible?)
2. The user could supply a name/handle for the window, which is opened on the first call, and then used for subsequent updates.  (This is what `OpenCV` does.)

I like option 2, but wanted to get feedback before implementing anything (e.g., if something like this is already possible.)

**Comment by timholy** [comment]
This is possible now.
