### ISSUE TITLE
Statistics from image data?

### ISSUE THREAD

**Issue by Jakki42** [JuliaImages/ImageView.jl#69]
Using Win 8.1.

mean(img) works just fine, but var(img) doesn't but just produces error:

ERROR: `varm` has no method matching varm(::Image{Gray{UfixedBase{Uint16,16}},2,Array{Gray{UfixedBase{Uint16,16}},2}},::Gray{Float32})
 in var at statistics.jl:162

Trying to operate just on the data with var(img.data) or var(data(img)) produces error:

ERROR: `varm` has no method matching varm(::Array{Gray{UfixedBase{Uint16,16}},2},::Gray{Float32})
 in var at statistics.jl:162

I noticed many other functions also don't like image data but work on regular arrays, so maybe this is just unfinnished functionality instead of bug?

Any easy workarounds for this?

**Comment by timholy** [comment]
Missing functionality. Please keep reporting such problems. I can't promise to get to it quickly, but if you make the report it raises the chances of it being implemented.

**Comment by Jakki42** [comment]
I'm not sure why I opened this in ImageView.jl and not in Image.jl, but I'll report a few more here (maybe I should report them there as well?):

Missing for ::Gray(UfixedBase{Uint16,16}} are at least:

./
sin, cos, tan etc.
std, var (as already mentioned earlier)
sqrt

Hopefully I'll learn Git and Julia well enough someday to be able to implement this kind of things myself, but not holding my breath :)

**Comment by timholy** [comment]
All these seem to have been fixed long ago in ColorVectorSpace.
