### ISSUE TITLE
reusing canvas with new 3D Image (ie, video) doesn't work

### ISSUE THREAD

**Issue by nstiurca** [JuliaImages/ImageView.jl#79]
I am using Julia v0.3.11, and I've run `Pkg.update()`. My OS is Linux Mint 17.2 (Ubuntu 14.04 based).

Consider that I have some videos stored as 3D `Image`s with the `timedim` property set. Then if I do

```
using ImageView
video1 = ...
video2 = ...
canv,_ = view(video1)
```

and everything looks great. However, if I later do

```
view(canv, video2)
```

then only the first frame loads correctly. Trying to change frames results in a pop-up `Application Error` with the Error

```
    while executing
"jl_cb0x2a94e792aa6e12e6 %xs 44.00995024875622"
    invoked from within
"$w set [$w get $x $y]"
    (procedure "ttk::scale::Drag" line 4)
    invoked from within
"ttk::scale::Drag .jl_win175.jl_ttk_frame178.jl_ttk_scale186 111 9 "
    (command bound to event)
```

If I instead do 

```
view(canvas(canv), video2)
```

then when I try to scroll, the `ImageView` reverts back to displaying the original video.

**Comment by timholy** [comment]
Thanks for the bug report. `view(canv, video2)` did not show the same Tk error for me, but I was using a 2nd video of the same size as the first.

This bug will not be easy to fix, because of a bad design decision on my part: packaging the image up into the `showframe` function (see the source code). But I'm getting close to starting on a major rewrite of ImageView, so I'll put this on the list of things to do better.

**Comment by nstiurca** [comment]
I see. As a workaround for my use case, maybe I can just close the canvas and replace it altogether. It looks like `get_size`/`set_size` work as I'd expect them, but I can't find anything regarding the position of the window. Am I missing something?

**Comment by timholy** [comment]
If you have an existing GUI and know the frame the canvas is in, you can just `destroy` the canvas and put a new one inside the same frame. Does that do what you want?

**Comment by timholy** [comment]
(I think `parent` will fetch the parent frame for you.)

**Comment by timholy** [comment]
Works now.
