### ISSUE TITLE
Error at view-call

### ISSUE THREAD

**Issue by rapus95** [JuliaImages/ImageView.jl#82]
Even though I assume that it's my fault, I got an error when calling the ImageView.view function with an additional canvas:

```
julia> x = (ImageView.view(img))[1]
ImageCanvas

julia> x
ImageCanvas

julia> ImageView.view(x,img)
ERROR: Tk.TclError("bad window path name \".jl_win20.jl_ttk_frame21.jl_ttk_frame22\"")
 in tcl_eval at C:<...>\.julia\v0.4\Tk\src\tkwidget.jl:96
```

**Comment by timholy** [comment]
Probably same as https://github.com/timholy/ImageView.jl/issues/79. It's reasonable to want this to work, but it's going to take some rewriting to make it happen. Try the destroy & recreate path outlined there.

**Comment by timholy** [comment]
No longer relevant (and works fine).
